export const SEMANTIC_CONSISTENCY_STATUS = Object.freeze({
  PASS: 'PASS',
  MISMATCH: 'MISMATCH',
  UNSUPPORTED: 'UNSUPPORTED',
})

export const SEMANTIC_CONSISTENCY_MODE = 'SHADOW_ONLY'
export const SEMANTIC_CONSISTENCY_AUTHORITY = 'SEMANTIC_CONSISTENCY_ONLY'

export const SEMANTIC_CONSISTENCY_DIAGNOSTIC = Object.freeze({
  REFERENCE: 'SEMANTIC_REFERENCE_DIAGNOSTIC',
  SOURCE_MISMATCH: 'SEMANTIC_SOURCE_MISMATCH',
  PROFILE_UNSUPPORTED: 'SEMANTIC_PROFILE_UNSUPPORTED',
  PART_COUNT_MISMATCH: 'SEMANTIC_PART_COUNT_MISMATCH',
  MEASURE_COUNT_MISMATCH: 'SEMANTIC_MEASURE_COUNT_MISMATCH',
  NOTE_COUNT_MISMATCH: 'SEMANTIC_NOTE_COUNT_MISMATCH',
  PITCH_MISMATCH: 'SEMANTIC_PITCH_MISMATCH',
  ONSET_MISMATCH: 'SEMANTIC_ONSET_MISMATCH',
  DURATION_MISMATCH: 'SEMANTIC_DURATION_MISMATCH',
  VOICE_MISMATCH: 'SEMANTIC_VOICE_MISMATCH',
  STAFF_MISMATCH: 'SEMANTIC_STAFF_MISMATCH',
  TIE_ROLE_MISMATCH: 'SEMANTIC_TIE_ROLE_MISMATCH',
  METER_MISMATCH: 'SEMANTIC_METER_MISMATCH',
})
