export { CORRECTION_STATUS, isCorrectionStatus } from './contracts/status.js'
export { EVIDENCE_SOURCE, createEvidence } from './contracts/evidence.js'
export { MIDI_REFERENCE_SOURCE_TYPE, MIDI_SCORE_PITCH_DOMAIN, MIDI_COMPARISON_CODE, isMidiReferenceSourceType, isMidiScorePitchDomain, isMidiComparisonCode, createMidiReferenceDiagnostic } from './contracts/midiReferenceEvidence.js'
export { PATCH_OPERATION, createCorrectionPatch } from './contracts/correctionPatch.js'
export { POLYPHONIC_ERROR_CLASS, POLYPHONIC_ERROR_TAXONOMY_VERSION, createErrorTaxonomyRef, isPolyphonicErrorClass } from './contracts/errorTaxonomy.js'
export { createCorrectionRequest } from './contracts/correctionRequest.js'
export { createCorrectionResult } from './contracts/correctionResult.js'
export { createScoreEvent } from './model/scoreEvent.js'
export { createMeasure } from './model/measure.js'
export { createScoreGraph } from './model/scoreGraph.js'
export { createCandidate } from './candidates/candidate.js'
export { DEFAULT_CANDIDATE_LIMITS, buildCandidateGraph } from './candidates/candidateGraph.js'
export { RESEARCH_CANDIDATE_OPERATION, DEFAULT_RESEARCH_CANDIDATE_LIMITS, generateBoundedResearchCandidates } from './candidates/researchCandidateGenerator.js'
export { CONSTRAINT_STATUS, evaluateMeterConstraint } from './constraints/meterConstraint.js'
export { evaluateOnsetConstraint } from './constraints/onsetConstraint.js'
export { detectOnsetAnomalies } from './constraints/onsetAnomalyDetector.js'
export { detectDurationAnomalies } from './constraints/durationConstraint.js'
export { detectTieAnomalies } from './constraints/tieConstraint.js'
export { detectTupletAnomalies } from './constraints/tupletConstraint.js'
export { DEFAULT_RESOLUTION_POLICY, resolveCandidates } from './resolver/candidateResolver.js'
export { genericScoreProfile, classicalGuitarProfile, pianoProfile, getInstrumentProfile } from './profiles/index.js'
export { VOICE_EVIDENCE_WEIGHTS, scoreVoiceAssignment } from './solver/voiceAssignmentScorer.js'
export { DEFAULT_VOICE_SOLVER_LIMITS, generateVoiceCandidates } from './solver/polyphonicVoiceSolver.js'
export { analyzeCrossStaffContext } from './solver/crossStaffAnalyzer.js'
export { revalidateProjectedRevisionV2 } from './validation/independentRevalidationV2.js'
export { CORRECTION_READINESS, evaluateCorrectionReadiness, readinessRequirements } from './readiness/productionReadiness.js'
export { createTeacherWorkloadTelemetry, aggregateTeacherWorkloadTelemetry } from './telemetry/teacherWorkloadTelemetry.js'
export { projectCorrectionPatches } from './correction/patchProjection.js'
export { revertCorrectionPatches } from './correction/patchReverter.js'
export { CONTROLLED_CORRECTION_DECISION, E11A_CONTROLLED_POLICY, applyControlledVoiceCorrection } from './correction/controlledAutoCorrection.js'
export { createTeacherApproval, createTeacherEvidence } from './evidence/teacherEvidence.js'
export { createVisualLocalizationEvidence } from './evidence/visualLocalizationEvidence.js'
export { createGoldCase } from './benchmark/goldCase.js'
export { runCorrectionBenchmark } from './benchmark/correctionBenchmark.js'
export { MIDI_EVALUATION_ORACLE_TYPE, createMidiEvaluationCase, runMidiEvidenceBenchmark } from './benchmark/midiEvidenceBenchmark.js'
export { MIDI_CORPUS_REQUIRED_SCENARIOS, evaluateMidiCorpusCoverage } from './benchmark/midiCorpusCoverage.js'
export { MIDI_RELIABILITY_STATUS, MIDI_RELIABILITY_REQUIRED_SOURCE_TYPES, createMidiTeacherGoldReliabilityReport } from './benchmark/midiTeacherGoldReliability.js'
export { REAL_MIDI_ORACLE_STATUS, ASAP_V1_1_BACH_BWV846_REFERENCE, REAL_MIDI_REFERENCE_REGISTRY, evaluateRealMidiReferenceAdmission, getRealMidiReferenceAdmission } from './benchmark/realMidiReferenceRegistry.js'
export { CORRECTION_EVENT_ORIGIN, TEACHER_DECISION, createTeacherGoldCorrectionEvent } from './benchmark/teacherGoldCorrectionEvent.js'
export { REAL_OMR_GOLD_REQUIRED_PROVENANCE, evaluateRealOmrGoldEligibility, createRealOmrCalibrationRecord, buildRealOmrCalibrationRecords } from './benchmark/realOmrGoldEligibility.js'
export { REAL_OMR_ANNOTATION_STATUS, createRealOmrReviewObservation, buildRealOmrAnnotationBatch, annotateRealOmrObservation } from './benchmark/realOmrAnnotationQueue.js'
export { createRealOmrEvidenceSplit, summarizeRealOmrEvidenceSplit } from './benchmark/realOmrEvidenceSplit.js'
export { APPROVED_REAL_OMR_SEED, createApprovedRealOmrSeedFixture, projectApprovedRealOmrNoCorrectionGold, summarizeApprovedRealOmrSeedGold } from './benchmark/approvedRealOmrSeed.js'
export { hashSourceBytes, evaluateSourceMutationInvariant } from './benchmark/sourceMutationInvariant.js'
export { evaluateSelectivePrediction, selectMetricAtThreshold } from './benchmark/selectivePredictionMetrics.js'
export { CALIBRATION_METHOD, evaluateConfidenceCalibration, compareCalibrationTransform } from './benchmark/confidenceCalibration.js'
export { describePolyphonyComplexity, polyphonyLevelLabel } from './benchmark/polyphonyComplexity.js'
export { createExternalBenchmarkManifest, evaluateExternalBenchmarkEligibility } from './benchmark/externalBenchmarkManifest.js'
export { CORPUS_SOURCE_STATUS, createCorpusSource, promoteCorpusSourceForGold } from './benchmark/corpusSource.js'
export { REFERENCE_CORPUS, getReferenceCorpusSource } from './benchmark/referenceCorpusRegistry.js'
export { REVIEW_PACKET_STATUS, createTeacherReviewPacket, approveTeacherReviewPacket, rejectTeacherReviewPacket, promoteReviewedSourceForGold } from './benchmark/teacherReviewPacket.js'
export { REFERENCE_REVIEW_QUEUE, getReferenceReviewPacket } from './benchmark/referenceReviewQueue.js'
export { TEACHER_APPROVALS, APPROVED_REVIEW_PACKETS, GOLD_ELIGIBLE_REFERENCE_CORPUS, getGoldEligibleReferenceSource } from './benchmark/approvedReferenceRegistry.js'
export {
  TEACHER_APPROVED_SOURCE_SPECIFIC_HIGH_EVIDENCE_CASES,
  TEACHER_APPROVED_SOURCE_SPECIFIC_GUARD_CASES,
  TEACHER_APPROVED_HIGH_EVIDENCE_CASES,
  TEACHER_APPROVED_GUARD_CASES,
  TEACHER_APPROVED_MUTATION_CASES,
} from './benchmark/teacherApprovedMutationCases.js'
